initial work
urfu-2017/javascript-task-8 pull request #12
Opened 2017-12-12 16:39 UTC by Admirallll

2017-12-12 16:40 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 23 из 23

2017-12-12 16:40 UTC, honest-hrundel commented
@Vittly обрати внимание: решено доп. задание

2017-12-12 16:57 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 23 из 23

2017-12-12 16:57 UTC, honest-hrundel commented
@Vittly обрати внимание: решено доп. задание

2017-12-12 17:04 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 23 из 23

2017-12-12 17:04 UTC, honest-hrundel commented
@Vittly обрати внимание: решено доп. задание

2017-12-12 18:11 UTC, honest-hrundel commented
:tomato: Пройдено тестов 29 из 31

2017-12-12 18:16 UTC, honest-hrundel commented
:tomato: Пройдено тестов 30 из 31

2017-12-12 18:22 UTC, honest-hrundel commented
:tomato: Пройдено тестов 22 из 23

2017-12-12 18:31 UTC, honest-hrundel commented
:tomato: Пройдено тестов 22 из 23

2017-12-12 18:35 UTC, honest-hrundel commented
:tomato: Пройдено тестов 22 из 23

2017-12-12 18:41 UTC, honest-hrundel commented
:tomato: Пройдено тестов 22 из 23

2017-12-12 18:42 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 23 из 23

2017-12-12 18:42 UTC, honest-hrundel commented
@Vittly обрати внимание: решено доп. задание

2017-12-12 18:46 UTC, honest-hrundel commented
:tomato: Пройдено тестов 22 из 23

2017-12-12 18:49 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-12-12 18:51 UTC, honest-hrundel commented
:tomato: Пройдено тестов 22 из 23

2017-12-12 18:54 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 23 из 23

2017-12-12 18:54 UTC, honest-hrundel commented
@Vittly обрати внимание: решено доп. задание

2017-12-12 18:58 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 31 из 31

2017-12-12 18:58 UTC, honest-hrundel commented
@Vittly обрати внимание: решено доп. задание

2017-12-13 04:43 UTC, Vittly requested changes
🍅

2017-12-13 04:43 UTC, Vittly commented on client-core.js
> +    if (command === 'list') {
`switch`

2017-12-13 04:43 UTC, Vittly commented on client-core.js
> +            .on('response', res => {
а обработка ошибок?

2017-12-13 04:43 UTC, Vittly commented on client-core.js
> +            form: JSON.stringify({ text }) })
`})` лучше перенести

2017-12-13 04:43 UTC, Vittly commented on client-core.js
> +            .on('response', res => {
тут и ниже. С сетью же работаем

2017-12-13 04:43 UTC, Vittly commented on server-core.js
> +    const { pathname, query } = url.parse(req.url, true);
уже парсили, не надо снова

2017-12-13 04:43 UTC, Vittly commented on server-core.js
> +        sendJsonResultWithMessage(res, result);
помоему тут messages должно быть) поэтому я бы оставил `sendJsonResult`

2017-12-13 04:43 UTC, Vittly commented on client-core.js
> +function readResponse(initialResponse) {
такая функция описана дважды, мб вынести в отдельынй файл общее?

2017-12-13 04:43 UTC, Vittly commented on server-core.js
> +    let id = md5(totalMessages.toString());
md5 от длины? Ооо может хотя бы от контента? или от длины + даты? или просто даты?

2017-12-13 16:10 UTC, Admirallll commented on client-core.js
> +            form: JSON.stringify({ text }) })
если перенести, то совсем некрасиво получается, убрал вообще переносы

2017-12-13 17:07 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 31 из 31

2017-12-13 17:07 UTC, honest-hrundel commented
@Vittly обрати внимание: решено доп. задание

2017-12-13 17:08 UTC, Admirallll commented on server-core.js
> +    let id = md5(totalMessages.toString());
хэш должен быть уникальным, md5 и так даёт коллизии, а тут ещё и если брать от не уникальных величин, то точно никакой уникальности не будет. Ну дату ещё можно, но зачем, вроде числовой индентефикатор тоже нормально

2017-12-14 14:25 UTC, Vittly commented on server-core.js
> +    let id = md5(totalMessages.toString());
тогда так: скажи пожалуйста, что такое `totalMessages.toString()` ? Это количество сообщений? Это число? Если так, то зачем делать md5? Почему просто не делать `'msg-id-${totalMessages.toString()}'`?

2017-12-14 14:27 UTC, Vittly commented
md5 меня слегка смущает в остальном ок

2017-12-14 14:27 UTC, Vittly requested changes
🍅

2017-12-14 14:27 UTC, Vittly commented on client-core.js
> +                    }
`reject`, если неизвестный статус?

2017-12-14 14:27 UTC, Vittly commented on http-helper.js
> +    });
`on('error', ...` бы еще

2017-12-17 11:31 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 31 из 31

2017-12-17 11:31 UTC, honest-hrundel commented
@Vittly обрати внимание: решено доп. задание

2017-12-18 08:41 UTC, Vittly approved these changes

2017-12-18 08:41 UTC, closed without merging