1
urfu-2017/javascript-task-8 pull request #4
Opened 2017-12-05 16:20 UTC by yuickhahirasawa

2017-12-05 16:21 UTC, honest-hrundel commented
:tomato: Хрюнделя очень расстроил твой код

2017-12-05 16:30 UTC, honest-hrundel commented
:tomato: Хрюнделя очень расстроил твой код

2017-12-05 16:33 UTC, honest-hrundel commented
:tomato: Хрюнделя очень расстроил твой код

2017-12-05 16:42 UTC, honest-hrundel commented
:tomato: Хрюнделя очень расстроил твой код

2017-12-05 16:52 UTC, honest-hrundel commented
:tomato: Хрюнделя очень расстроил твой код

2017-12-05 16:57 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-12-05 17:14 UTC, honest-hrundel commented
:tomato: Хрюнделя очень расстроил твой код

2017-12-05 17:15 UTC, honest-hrundel commented
:tomato: Хрюнделя очень расстроил твой код

2017-12-05 17:19 UTC, honest-hrundel commented
:tomato: Хрюнделя очень расстроил твой код

2017-12-05 17:24 UTC, honest-hrundel commented
:tomato: Хрюнделя очень расстроил твой код

2017-12-05 17:29 UTC, honest-hrundel commented
:tomato: Пройдено тестов 25 из 26

2017-12-05 17:44 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 18

2017-12-05 17:51 UTC, honest-hrundel commented
:tomato: Пройдено тестов 25 из 26

2017-12-05 18:01 UTC, honest-hrundel commented
:tomato: Пройдено тестов 25 из 26

2017-12-05 18:07 UTC, honest-hrundel commented
:tomato: Пройдено тестов 25 из 26

2017-12-05 19:28 UTC, honest-hrundel commented
:tomato: Пройдено тестов 25 из 26

2017-12-05 19:33 UTC, honest-hrundel commented
:tomato: Пройдено тестов 25 из 26

2017-12-05 19:36 UTC, honest-hrundel commented
:tomato: Пройдено тестов 25 из 26

2017-12-05 19:44 UTC, honest-hrundel commented
:tomato: Пройдено тестов 25 из 26

2017-12-05 19:50 UTC, honest-hrundel commented
:tomato: Пройдено тестов 25 из 26

2017-12-05 19:53 UTC, honest-hrundel commented
:tomato: Пройдено тестов 24 из 26

2017-12-05 19:58 UTC, honest-hrundel commented
:tomato: Пройдено тестов 25 из 26

2017-12-05 20:09 UTC, honest-hrundel commented
:tomato: Пройдено тестов 25 из 26

2017-12-05 20:21 UTC, honest-hrundel commented
:tomato: Пройдено тестов 25 из 26

2017-12-05 20:24 UTC, honest-hrundel commented
:tomato: Пройдено тестов 25 из 26

2017-12-06 08:39 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 31 из 31

2017-12-06 08:39 UTC, honest-hrundel commented
@nex2hex обрати внимание: решено доп. задание

2017-12-06 16:25 UTC, nex2hex requested changes
🍅

2017-12-06 16:25 UTC, nex2hex commented on Chat.js
> +        let messageForEdit = this._messages.filter(message => message.id === id);
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2017-12-06 16:25 UTC, nex2hex commented on Chat.js
> +        let cond = () => true;
применение пустой функции - затратная операция, в этом случае лучше сразу отдавать `this._messages`

```
if (from && to) {
    return this._messages.filter(...);
}

if (from) {
}

if (to) {
}

return this._messages;
```

2017-12-06 16:25 UTC, nex2hex commented on Chat.js
> +        if (from !== null && to !== null) {
`null` - в js означает "нет объекта". Для тех ситуаций, когда что-то ожидает объект, но его нет:

```
typeof null === "object"
```

когда значения нет, надо использовать undefined

2017-12-06 16:25 UTC, nex2hex commented on ChatClient.js
> +            return Promise.resolve('DELETED');
может все-таки правильнее return `Promise.reject(...)` ?

2017-12-06 16:25 UTC, nex2hex commented on ChatClient.js
> +        return new Promise((resolved, reject) => {
`resolve`

2017-12-06 16:25 UTC, nex2hex commented on ChatClient.js
> +        return `http://${this._host}:${this._port}/messages`;
`this._host` и `this._port` не изменяются во время выполнения процесса. Есть смысл перенести это в constructor

2017-12-06 16:25 UTC, nex2hex commented on ChatClient.js
> +            request({
как-то коряво, когда в одном месте встречаются `Promise` и `callback`. Может есть смысл в https://github.com/request/request-promise или https://www.npmjs.com/package/got#gotgeturl-options ? (второй вариант на мой взгляд удобнее)

2017-12-06 16:25 UTC, nex2hex commented on ChatClient.js
> +        let query = this._getQuery([
```
const querystring = require('querystring'); // стандартный модуль в ноде
const query = querystring.stringify({
    from: from,
    to: to
});
const addr = `${this._url}?${query}`;
```

2017-12-06 16:25 UTC, nex2hex commented on ChatClient.js
> +                    JSON
https://www.npmjs.com/package/got#json

2017-12-06 16:25 UTC, nex2hex commented on ChatClient.js
> +    _chalk(message, ext) {
красить текст надо непосредственно перед выводом на консоль, чат не должен знать куда и как сообщения из него будут использоваться

2017-12-06 16:25 UTC, nex2hex commented on client-core.js
> +function parseArgs(args) {
https://www.npmjs.com/package/minimist

2017-12-06 16:25 UTC, nex2hex commented on client-core.js
> +        let result = parsedArgs.command === 'send' || parsedArgs.command === 'list'
какие-то костыли

почему не вызывать  client.send / client.list / ... прямо тут?

2017-12-06 16:57 UTC, yuickhahirasawa commented on Chat.js
> +        let messageForEdit = this._messages.filter(message => message.id === id);
Исправил. Всё время про них забываю.

2017-12-06 17:01 UTC, yuickhahirasawa commented on Chat.js
> +        let cond = () => true;
И правда. Исправил. Просто единообразия хотелось.

2017-12-06 17:04 UTC, yuickhahirasawa commented on Chat.js
> +        if (from !== null && to !== null) {
Можно и так, убрал.

2017-12-06 17:05 UTC, yuickhahirasawa commented on Chat.js
> +        const message = {
+

2017-12-06 17:05 UTC, yuickhahirasawa commented on ChatClient.js
> +            return Promise.resolve('DELETED');
В данном случае не особо важно, в условиях это не оговаривалось.

2017-12-06 17:07 UTC, yuickhahirasawa commented on ChatClient.js
> +        return new Promise((resolved, reject) => {
Простите за мой английский.

2017-12-06 17:07 UTC, yuickhahirasawa commented on ChatClient.js
> +            request({
Хотел без использования сторонних библиотек.

2017-12-06 17:09 UTC, yuickhahirasawa commented on ChatClient.js
> +        let query = this._getQuery([
Не знал, исправлю.

2017-12-06 17:10 UTC, yuickhahirasawa commented on ChatClient.js
> +                    JSON
Не хочу использовать внешние библиотеки.

2017-12-06 17:10 UTC, yuickhahirasawa commented on ChatClient.js
> +    _chalk(message, ext) {
Согласен, сглупил. Вынесу.

2017-12-06 17:10 UTC, yuickhahirasawa commented on ChatClient.js
> +        return `http://${this._host}:${this._port}/messages`;
Это с заделом на будущее )

2017-12-06 17:11 UTC, yuickhahirasawa commented on client-core.js
> +function parseArgs(args) {
Не хочу внешние библиотеки.

2017-12-06 17:29 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 31 из 31

2017-12-06 17:29 UTC, honest-hrundel commented
@nex2hex обрати внимание: решено доп. задание

2017-12-07 09:30 UTC, nex2hex requested changes
🍅

2017-12-07 09:30 UTC, nex2hex commented on ChatClient.js
> +            return Promise.reject('DELETED');
`return Promise.reject('Empty id');`

2017-12-07 09:30 UTC, nex2hex commented on ChatClient.js
> +        if (!id || !text || text === '') {
`text === ''` можно убрать. Первая проверка включает в себя пустую строку

2017-12-07 09:30 UTC, nex2hex commented on client-core.js
> +    return new Promise(async (resolved) => {
`resolve`

2017-12-07 09:30 UTC, nex2hex commented on client-core.js
>  function execute() {
```
async function execute() {
    command = parsedArgs.command;
    if (ACCEPT_COMMANDS.indexOf(parsedArgs.command) === -1) {
        return;
    }

    if (command === 'send') {
        const message = await client.send(params.text, params.from, params.to);
        return chalkMessage(message, params.v);
    }
    ...
}
```

2017-12-07 09:30 UTC, nex2hex commented on server-core.js
> +    if (req.method === 'POST' || req.method === 'PATCH') {
```
if (req.method === 'POST' || req.method === 'PATCH') {
    data = await getData(req);
}
```

2017-12-07 09:30 UTC, nex2hex commented on server-core.js
> +        if (req.method === 'POST' || req.method === 'PATCH') {
а тут эту проверку вообще убрать можно

2017-12-07 09:30 UTC, nex2hex commented on server-core.js
> +        const result = createOrGetMethod
тоже можно все переписать как и в client-core.js

2017-12-07 09:30 UTC, nex2hex commented on server-core.js
> +function parsePath(urlStr, method) {
вся эта функция - один большой костыль

я бы сделал как-то так в основной функции

```
const id = /messages\/(\d+)/.exec(url.pathname)[1]
if (!id) {
    res.writeHead(400);
}
```

2017-12-07 11:34 UTC, yuickhahirasawa commented on ChatClient.js
> +            return Promise.reject('DELETED');
В условиях ничего об этом нет, поэтому сделано как там.

2017-12-07 11:36 UTC, yuickhahirasawa commented on ChatClient.js
> +        if (!id || !text || text === '') {
+

2017-12-07 12:14 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 31 из 31

2017-12-07 12:14 UTC, honest-hrundel commented
@nex2hex обрати внимание: решено доп. задание

2017-12-07 13:10 UTC, honest-hrundel commented
:tomato: Пройдено тестов 30 из 31

2017-12-07 13:11 UTC, honest-hrundel commented
:tomato: Пройдено тестов 30 из 31

2017-12-07 13:13 UTC, honest-hrundel commented
:tomato: Пройдено тестов 30 из 31

2017-12-07 13:40 UTC, honest-hrundel commented
:tomato: Пройдено тестов 28 из 31

2017-12-07 13:41 UTC, honest-hrundel commented
:tomato: Пройдено тестов 28 из 31

2017-12-07 13:42 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 31 из 31

2017-12-07 13:42 UTC, honest-hrundel commented
@nex2hex обрати внимание: решено доп. задание

2017-12-07 14:01 UTC, nex2hex commented
🍏

2017-12-07 14:01 UTC, closed without merging